// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azhostewywrswibudjal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6aG9zdGV3eXdyc3dpYnVkamFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTgyMDYsImV4cCI6MjA2ODc3NDIwNn0.cqjMkv8-fF6jTRSS_Z3HQq4QDi0loMivitA-W-4eohw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});